//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTCD1_TAQ_2210900058_PJ2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietPhienChoi
    {
        public int ma_chi_tiet { get; set; }
        public Nullable<int> ma_phien { get; set; }
        public Nullable<int> ma_may_tinh { get; set; }
        public System.DateTime thoi_gian_vao { get; set; }
        public Nullable<System.DateTime> thoi_gian_ra { get; set; }
        public Nullable<decimal> thoi_luong { get; set; }
    
        public virtual MayTinh MayTinh { get; set; }
        public virtual PhienChoi PhienChoi { get; set; }
    }
}
