//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTCD1_TAQ_2210900058_PJ2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GiaoDich
    {
        public int ma_giao_dich { get; set; }
        public Nullable<int> ma_nguoi_dung { get; set; }
        public string loai_giao_dich { get; set; }
        public decimal so_tien { get; set; }
        public Nullable<System.DateTime> ngay_giao_dich { get; set; }
    
        public virtual NguoiDung NguoiDung { get; set; }
    }
}
