//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTCD1_TAQ_2210900058_PJ2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhienChoi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PhienChoi()
        {
            this.ChiTietPhienChois = new HashSet<ChiTietPhienChoi>();
        }
    
        public int ma_phien { get; set; }
        public Nullable<int> ma_nguoi_dung { get; set; }
        public Nullable<int> ma_may_tinh { get; set; }
        public System.DateTime thoi_gian_bat_dau { get; set; }
        public Nullable<System.DateTime> thoi_gian_ket_thuc { get; set; }
        public Nullable<decimal> tong_thoi_gian { get; set; }
        public Nullable<decimal> tong_chi_phi { get; set; }
        public string trang_thai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietPhienChoi> ChiTietPhienChois { get; set; }
        public virtual MayTinh MayTinh { get; set; }
        public virtual NguoiDung NguoiDung { get; set; }
    }
}
